### PR TITLE
Update deps, new hiding method, fix tests randomly failing

### PR DESCRIPTION
**Pull request by Displax**
* Implement new hiding method (February 2023)
* Fix KeyStore hook desynchronization (tests randomly failing problem)
* Fix crash and endless tests loop/failing with debugging ON on Android < 9.0
* Updated libcxx to upstream
* Able to build with NDK 25.2
* Updated AGP and deps

Tests: BUILD SUCCESSFUL && SN: ctsProfileMatch: true, basicIntegrity: true | PI: MEETS_BASIC_INTEGRITY, MEETS_DEVICE_INTEGRITY

### CODE REVIEW

**Comment by Rancoeur** [comment]
There is weird behaviour that the integrity checks fail right after boot but after a few minutes they pass again.
This makes the wallet button in QS unusable and for GPay to not be active in apps that detect it.

**Comment by Displax** [comment]
> There is weird behaviour that the integrity checks fail right after boot but after a few minutes they pass again. This makes the wallet button in QS unusable and for GPay to not be active in apps that detect it.
> 
> Update: Contactless payment works after checks have been passed. Only running this fork's version of USNF on my Android 13.

Fixed now.

**Comment by Catfriend1** [comment]
Good work, lgtm and beta please.

**Comment by pannal** [comment]
On my nothing phone 1 (1.1.8) your 2.4.0-MOD_1.1 fails safetynet in both counts after a while (half an hour), after working initially.

2.3.1-MOD_3.0 works fine.

Please let me know how to help.

**Comment by Rancoeur** [comment]
Works on my device with commit 11b3fed right after boot.

**Comment by pannal** [comment]
Thank you, fixed with 2.4.0-MOD_1.2

**Comment by j0110** [comment]
Well, it fails with 2.4.0_MOD_1.2, but was working with 2.3.1-MOD_3.0...
Screenshot_20230215-164152_Settings
Screenshot_20230215-164132_Yet Another SafetyNet Attestation Checker

**Comment by Catfriend1** [comment]
With latest displax mod:
Screenshot_20230218-105548_Yet Another SafetyNet Attestation Checker

**Comment by Catfriend1** [comment]
Just a sidenote: I can pass both tests in yasnac fine with thw recent displax mod. I've then tried to disable Shamiko 0.6 additionally and still, both profiles passed - but then Wallet detected "not meeting security requirements" and I had to reenable shamiko plus clear play services cache to make it meet requirements again. How can they still detect the magisk even when both profiles pass?

**Comment by CRCinAU** [comment]
Moved from MOD_1 to MOD_1.2 and can confirm that the random failures seem to be resolved.

**Comment by NBruderman** [comment]
> Just a sidenote: I can pass both tests in yasnac fine with thw recent displax mod. I've then tried to disable Shamiko 0.6 additionally and still, both profiles passed - but then Wallet detected "not meeting security requirements" and I had to reenable shamiko plus clear play services cache to make it meet requirements again. How can they still detect the magisk even when both profiles pass?

I had a similar experience with Magisk. Wallet worked fine, and one day I hid the magisk app. Suddenly, the "not meeting security requirements" appeared. Then I un-hid magisk, and everything went back to normal. I didn't even need to clear anything. So weird.

**Comment by Catfriend1** [comment]
@kdrag0n how to go on ?

**Review by adipascu — APPROVED** [review]

**Comment by notAxion** [comment]
passes on my poco f1
with awaken os 3.4
Screenshot_20230605-185137_Pixel Launcher

**Comment by adipascu** [comment]
@Displax why was this closed?

**Comment by Displax** [comment]
> @Displax why was this closed?

Because this PR messed by my mod. Just live this as an example if kdrag0n wants to see it.

**Pull request closed without merging**
