### PR TITLE
Include native properties only

### PR DESCRIPTION
**Pull request by ipdev99**
Generate the 'system.prop' file during the module install/update.
~~Generate the 'system.prop' file on first boot in post-fs-data mode after install/update.~~

Only include the 'property' if it currently exists on the device.
This will keep the device closer to stock by not adding properties that are device (manufacture) specific.

### CODE REVIEW

**Comment by ipdev99** [comment]
A bit tricky to explain the reason why this change will not work correctly. :upside_down_face:

This change will check if the prop exists before adding it to the `system.prop` file.
_Also a check in the `service` script to make sure late set props exist and if they need to be reset._

The current version of this module sets all the props regardless if they exist.
Since it is using a `system.prop` file, the values are set before service scripts are run.
This means other modules like MagiskHide Props Config will find the _sensitive_ properties set by this module and include it.

This update/change will only work on a 'clean' boot.
_The change works regardless.
Unless it is a clean boot it will also include sensitive props that were falsely added prior._

The current version of this module and other modules that adjust sensitive properties need to be disabled.
_The other modules may need to be reset to forget the properties they found before so they do not add them again._


The alternative option would be to move it into the service script.
_This would also allow us to only set the prop if it not safe._

The disadvantage is there is no control on when a service script runs.
No way to make sure this module's scripts run before another module's scripts.
_Only an observation but, it seems it might have to do with the initial install (module directory) date/time. :thinking:_


Note(s):
I might be wrong on when `system.prop` files are run.
_I looked though the Magisk documentation and I did not find (or missed) when the props are actually added/changed.
Either an old memory or just an observation. :thinking:_

Normally...
You can turn on 'Airplane mode' before disabling modules and rebooting.
Make changes, enable modules again and reboot.
Then tun off 'Airplane mode' to keep _Play certification_.

:cowboy_hat_face:

**Comment by osm0sis** [comment]
Rather than excluding things from the prop file it could just be converted to a post-fs-data.d script, which would be more self-documenting, and would not depend on the install environment being accurate.

**Comment by ipdev99** [comment]
I thought about moving it all into the service script.
This way would be dynamic and we can check and correct as necessary during boot.

I would be hesitant to set everything in post-fs-mode.
It is possible the props will not take or might revert when boot continues.

The Magisk docs mention about post-fs-mode.
_**Only run scripts in this mode if necessary.**_

Didgeridoohan's _MagiskHide Props Config_ module has better documentation on setting prop values and [boot stages](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/README.md#boot-stage).

Since the service script runs in late start, it is possible the props will be set too late.

Seems the best way is to use a 'system.prop' file and let Magisk load the prop values after post-fs and before late boot.

Since using a 'system.prop' file is static.
This is why I decided to include the safe value if the prop exists even if it is already the safe value.
Just in case the value is changed after the 'system.prop' file is generated.

What if we use a one shot post-fs script to generate a 'system.prop' file on initial boot after installing the module? :thinking:

**Comment by osm0sis** [comment]
If you check out magisk.log it honestly doesn't seem like system.prop is much later than a module post-fs-data.sh

**Comment by ipdev99** [comment]
I and others have run into bootloops, stuck in an infinite boot or unexpectedly invited into Recovery party when setting some properties on some devices during post-fs-mode. :upside_down_face:
_This is based on using the MagiskHide Props Config module._

Since I do not have a Samsung, newer OnePlus or a Xiaomi (China) device to test on.
I can not guarantee it will not cause an issue if the props are set during post-fs-data.
_I have a 'post-fs-data.sh' and a 'service' script ready to go but, I do not want to push it until I can test it across more devices.
I have a China ROM installed on my Poco F2 Prop but, it does not return `ro.boot.hwc` or `ro.boot.hwcountry` so I can not test those commands/changes along with some others._

For now I opted to generate a 'system.prop' file on the initial boot (during post-fs) after install.

**Comment by ipdev99** [comment]
Took me longer than it should have to make it to work. :upside_down_face:

I know I was told double brackets was not compatible.
[Magisk PR](https://github.com/topjohnwu/Magisk/pull/5070#issuecomment-1009665079)
_Setting a local command variables in a function may not have helped. :thinking:_

I gave up on making it work in post-fs using double quotes on variables and reverted back to using double brackets and no local variables within the function.
_There are a lot of Android/Magisk scripts that use double brackets without error._

Since I was in my testing branch, it also includes my other [PR](https://github.com/kdrag0n/safetynet-fix/pull/150).
If all approve I will close the other [PR](https://github.com/kdrag0n/safetynet-fix/pull/150) and squash all the commits into this one.

Cheers all. :cowboy_hat_face:

**Comment by ipdev99** [comment]
Reverted back to generating the 'system.prop' file during the module install/update for now. :upside_down_face:

**Review by Trinacristella — APPROVED** [review]

**Comment by osm0sis** [comment]
is_ever_orange took like 32 seconds after boot_completed for me

**Comment by ipdev99** [comment]
Bummer. :disappointed:

I did some rewriting to my alternative _(dynamic)_ [service script](https://github.com/ipdev99/safetynet-fix/blob/dynamic/magisk/service.sh).
_Check if the prop exists or 10 seconds after boot complete. Which ever comes first._

Seems I will have to rethink that idea again. :thinking:

:cowboy_hat_face:

**Comment by ipdev99** [comment]
Closed this PR for now.

I will do some more testing and open a new PR when ready. :upside_down_face:

**Comment by ipdev99** [comment]
Closed this PR for now.

I will do some more testing and open a new PR when ready. :upside_down_face:

**Pull request closed without merging**
