### PR TITLE
Minor reduction of confusion re Magisk v23/24

### PR DESCRIPTION
**Pull request by TAbdiukov**
MagiskHide Props Config does not support Magisk v24, so it may be worthwhile mentioning to the newer users.

[Related issue](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/142)

### CODE REVIEW

**Comment by HuskyDG** [comment]
There is no need to use MagiskHide Props Config.
If you want to change fingerprint, why not just create a simple `resetprop` script or simple `system.prop` module 🤷

**Comment by pndwal** [comment]
@kdrag0n

We generally won't need to set fingerprint any longer to pass CTS Profile match for either old S/N or new PI deviceIntegrity even in custom, China region, developer, beta uncertified ROMs etc w/ USNF 2.4.0 because we now have mismatched but passing fingerprint set for gms natively and working for all devices I'm aware of, so readme wording does need adjusting...

> MagiskHide Props Config does not support Magisk v24, so it may be worthwhile mentioning to the newer users.
> 
> [Related issue](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/issues/142)

This statement is false however; while @Didgeridoohan hasn't updated it lately (and is busy with life) MHPC certainly still works fine W/ Magisk 24+!!!... The linked issue is only asking for module update notification support since we got JSON based updates instead of notifications through old repo...

MHPC can still be used with no inherent problems w/ latest Magisk and may still be useful in some edge cases, I don't know, but the statement "[MagiskHide Props Config is an easy way to do so on Magisk v23 and older" will only cause confusion.

**Comment by TAbdiukov** [comment]
OP here. Thanks @pndwal ! I can confirm that I was unintentionally mistaken, and this PR is NOT to be merged. Thanks!

**Comment by TAbdiukov** [comment]
Let's continue future discussion at https://github.com/kdrag0n/safetynet-fix/issues/255

**Comment by pndwal** [comment]
> OP here. Thanks @pndwal ! I can confirm that I was unintentionally mistaken, and this PR is NOT to be merged. Thanks!

👍 ... Well this was already merged on Jan 7... (See above; go to README.md line 7 re. Magisk 23 etc.)

Of course MHPC now serves no purpose with USNF, so this all needs rewording again anyway... 😜

**Pull request closed without merging**
