### PR TITLE
Include native properties only (Take Two :clapper: ).

### PR DESCRIPTION
**Pull request by ipdev99**
Only include the 'property' if it currently exists on the device.
This will keep the device closer to stock by not including properties that are device (manufacture) specific to the ```system.prop``` file.

---
This turned into a bit more than just a simple PR. :upside_down_face:
_The shell scripts have been mostly rewritten in the process._

Switched to using Magisk's ```-n``` option for resetprop.
[Magisk Resetprop](https://topjohnwu.github.io/Magisk/details.html#resetprop).

Updated the shell script(s) to be less _'bash'_ and more _'ash'_ for better compatibility.

_This is my current (updated) version of PR https://github.com/kdrag0n/safetynet-fix/pull/158_

### CODE REVIEW

**Comment by ipdev99** [comment]
The system.prop file is generated during the install.
This allows us to check if the prop exists before adding it to system.prop file.
The service script now checks if the prop exists and adjusts it to the safe value if needed.

Known issue.
Since the current version of this module includes all the prop(s), manufacture specific props will still be found and included during the install.
A clean install of the module would be needed to keep manufacture specific props from being included on all devices.
_Future updates should not be an issue. :crossed_fingers:_

:cowboy_hat_face:

**Comment by ipdev99** [comment]
Why is it unnecessary?
Never mind.

This seems to be the mentality on Github lately.

Fuck it.
PR closed. :thumbsup:

Cheers. :cowboy_hat_face:

**Comment by kdrag0n** [comment]
This isn't strictly necessary, but that doesn't mean it's not worth having. That being said, though, this approach as it stands wouldn't be accepted. Please don't rewrite the scripts or ignore the existing code style, especially wrt. redundant comments and variable naming.

More importantly, this seems to include a lot of unrelated changes beyond the description. I think the core idea of not adding properties that don't already exist would only take a few lines of changes to implement. Why are all the other changes necessary?

**Comment by ipdev99** [comment]
The rewrite was primarily to replace double bracketed statements with single bracketed statements.
Double brackets seem to still work but, I was politely reminded that is bash only.
_[Magisk PR Comment](https://github.com/topjohnwu/Magisk/pull/5070#issuecomment-1009665079)_

_That comment (reminder) reminded me of a [correction](https://github.com/ipdev99/mHideGP/commit/6de727d1c98f0a755aec15462614ea3151d639db) I made previously in a project that I was trying to make work across platform.
Android, Linux and MacOS._

---

The changes I made in the script files.
- Noted Magisk's built in variables.
- Set functions instead of writing "if-then" statements for everything.
_Each function checks if the prop exists then runs the rest of the function._

---

The current customize script is not much of anything.

It currently only checks the SDK version and then removes only the zygisk part of the module if it is below SDK26.
Then changes the permissions to 0755 on both the service and post-fs script files.

Magisk already finds the current SDK version of the device, the built in "API" variable.
Instead of 
```if [[ "$(getprop ro.build.version.sdk)" -lt 26 ]]; then```
You can do the same with.
```if [ "$API" -lt 26 ]; then```

Since the post-fs script is not removed on Android 7.x and below, gms will still be removed from Magisk's denylist when enforcing.

This works against the user on older Android.
Enforcing the denylist and including Safetynet ```com.google.android.gms.unstable``` and sometimes the main process ```com.google.android.gms``` is one way to pass SafetyNet.
So the post-fs script also needs to be removed for Android 7.x support.

Since the current customize script manually sets both service and post-fs scripts to 0755, it will give error is the post-fs script is missing.

Easy (future proof) way is just to change the permissions of the module scripts that exist.
``` # Correct permissions of the script file(s).
for i in "$MODPATH"/*.sh; do
    chmod 0755 $i
done
```

---

The current service script needed a bit of cleanup also.
Again, instead of using multiple "if-then" statements, I turned to using functions.
_This also makes the scripts more uniform since the formatting is the same._

Changed
```
# Avoid breaking encryption, set shipping level to 32 for devices >=33 to allow for software attestation
if [[ "$(getprop ro.product.first_api_level)" -ge 33 ]]; then
  resetprop ro.product.first_api_level 32
fi
```

To (using the "set_max" function.)
```
set_max() {
  if [ "$(getprop $1)" ]; then
    if [ "$(getprop $1)" -gt "$2" ]; then
      resetprop -n $1 $2
    fi
  fi
}
set_max ro.product.first_api_level 32
```

No reason we could not add notes to the line.
```
set_max ro.product.first_api_level 32 # Avoid breaking encryption, set shipping level to 32 for devices >=33 to allow for software attestation
```

I included the "set_min" function just to be more future proof.
_Who knows if we find another generic or Manufacture specific prop value we need to set a min or max value.
Who knows what MiUi-Redmi-Xiaomi, OnePlus-OPPO, Samsung, ... will do._

**Comment by ipdev99** [comment]
>More importantly, this seems to include a lot of unrelated changes beyond the description. I think the core idea of not adding properties that don't already exist would only take a few lines of changes to implement. Why are all the other changes necessary?

There might be. :upside_down_face: 
I have not had time to test the Android 7.x part lately to make sure it still works, so I did not include it in this PR.

I pushed my current full variation to a new test branch.
[USNF-Testing](https://github.com/ipdev99/usnf/commit/91e95eb2c4008ca2e79a30995e6b6e9ac6e37fed)

Hope it helps explains more than confuse. :thinking:

Cheers. :cowboy_hat_face:

**Comment by ipdev99** [comment]
> All props in `system.prop` are guaranteed to usually exist in almost ROMs and no need to change. No app can't try to detect them.

Have you ever checked multiple devices and across manufactures. :unamused:

OnePlus's ```ro.is_ever_orange``` is a prop that comes to mind.
This does <b>not</b> exist on older OnePlus devices.
_Google Nexus/Pixel, Samsung, or Xiaomi devices._

Cheers. :cowboy_hat_face:

**Comment by ipdev99** [comment]
> Don't you see this is unnecessary? Why would we need to add additional unnecessary logic?
> 
> > Changed
> > ```
> > # Avoid breaking encryption, set shipping level to 32 for devices >=33 to allow for software attestation
> > if [[ "$(getprop ro.product.first_api_level)" -ge 33 ]]; then
> >  resetprop ro.product.first_api_level 32
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To (using the "set_max" function.)
> > ```
> > set_max() {
> >  if [ "$(getprop $1)" ]; then
> >    if [ "$(getprop $1)" -gt "$2" ]; then
> >      resetprop -n $1 $2
> >    fi
> >  fi
> > }
> > set_max ro.product.first_api_level 32
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No reason we could not add notes to the line.
> > ```
> > set_max ro.product.first_api_level 32 # Avoid breaking encryption, set shipping level to 32 for devices >=33 to allow for software attestation
> > ```



> Bad idea
> 
> > Easy (future proof) way is just to change the permissions of the module scripts that exist.
> > ```
> > for i in "$MODPATH"/*.sh; do
> >    chmod 0755 $i
> > done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The current service script needed a bit of cleanup also.
> > Again, instead of using multiple "if-then" statements, I turned to using functions.

:rofl:

**Pull request closed without merging**
