### PR TITLE
Shim the keystore service instead of replacing it

### LINKED ISSUE #3: Phone soft reboots after applying fix.
**This isn't really an issue** but when I apply the fix onto my phone and restart, the phone restarts again (shows boot screen), then it works fine shortly after. Why does this happen?

### LINKED ISSUE #32: Support for heavily-customized OEM ROMs (e.g. One UI, MIUI)
## For users

Universal SafetyNet Fix is not compatible with heavy OEM skins such as Samsung One UI and MIUI. You can try it at your own risk, but don't expect it to work. Instability and/or bootloops are likely. **Common issues include broken fingerprint unlocking, broken biometric authentication in apps, crashing apps, and more.**

### DO NOT report issues if you are using a heavy OEM skin.

---

## For developers

Replacing the keystore service causes breakage on heavily-customized OEM ROMs where the vendor has made intrusive changes that don't work with the AOSP keystore service. The most prominent example of this is Samsung One UI, but there are other vendors doing this.

Patching the keystore service executable is not a scalable solution, so this needs to be fixed another way. The current proposal is to shim the system's existing service (#13, blocked by #33), but I'm open to other ideas.

Feel free to propose alternative ideas or submit an implementation PR.

### PR DESCRIPTION
**Pull request by kdrag0n**
This method is more portable, does not require a different executable for each Android version, and avoids breaking ROMs with heavy keystore customizations. It works by injecting a shared library into the keystore service and wrapping the Binder transaction handler in the generated AIDL interface.

Because the actual attestKey implementation is statically linked into the keystore service executable, we can't hijack it directly without messy and error-prone code patching. Instead, we check each Binder transaction handled by the AIDL stub and hijack transactions with the TRANSACTION_attestKey code.

In order to keep key attestation working for apps, we only block Google Play Services by checking the command line of the calling process through Binder. This is not infallible and can be spoofed, but it's much easier to do in C++ than looking up the calling UID's package name through PackageManagerService. There are no negative security implications as the only difference is a denied operation.

We can't set LD_PRELOAD for the keystore service because Magisk modules start too late to modify its init.rc, so we inject the shim library as a dependency instead using patchelf and build it with the DF_1_GLOBAL ELF flag to make the dynamic linker prioritize it in symbol resolution.

TRANSACTION_attestKey values and AIDL stub names by Android version:
```
Android 10 - 11     (SDK 29-30): TX# 28, android::security::keystore::BnKeystoreService
Android 9           (SDK 28   ): TX# 35, android::security::BnKeystoreService
Android 7.0 - 8.1.0 (SDK 24-27): TX# 36, android::BnKeystoreService
```

**This needs testing in many different scenarios before it can be considered stable.**

Fixes #32.

Blocked by #33.

## Scenarios and issues to test

- 32-bit ARM devices
- Heavy OEM skins
- Samsung One UI
- MIUI
- Broken biometric authentication in apps
- Unstable system (i.e. rebooting and/or crashing)

### CODE REVIEW

**Comment by kdrag0n** [comment]
Initial test build: [safetynet-fix-v2.0.0-test1.zip](https://github.com/kdrag0n/safetynet-fix/files/5876072/safetynet-fix-v2.0.0-test1.zip)

**Comment by jkaetz** [comment]
> Initial test build: [safetynet-fix-v2.0.0-test1.zip](https://github.com/kdrag0n/safetynet-fix/files/5876072/safetynet-fix-v2.0.0-test1.zip)
@kdrag0n 
Tested on a Tab S6.  Safetynet in Magisk reports a ctsProfile failure in hardware mode.  Is there a secure location I can share the logcat with you?

**Comment by ionn28** [comment]
Using MIUI11 A9. Got ctsProfile failure with BASIC evalType. Fingerprints work though.

**Comment by kdrag0n** [comment]
Fixed build:  [safetynet-fix-v2.0.0-test2.zip](https://github.com/kdrag0n/safetynet-fix/files/5876482/safetynet-fix-v2.0.0-test2.zip)

The issues have nothing to do with the solution itself, there was just something missing in the Magisk module.

**Comment by jbro129** [comment]
Tested you test2 zip on my Galaxy S20+ running android 11 and One UI 3.0. SafetyNet passes and biometric authentication seems to be working as well (Tested with paypal and my banking app). 
So far no rebooting or crashes. 
If any crashes or rebooting occur I'll update this comment or post another about it.

**Comment by ionn28** [comment]
Flashed new build on MIUI. CtsProfile still fails.

**Comment by nampud** [comment]
Android 10 One UI 2.5 on my device:
patchelf fails to run at boot:
```CANNOT LINK EXECUTABLE "/data/adb/modules/safetynet-fix/_bin/patchelf": cannot locate symbol "_Unwind_Resume" referenced by "/data/adb/modules/safetynet-fix/_bin/patchelf"...```
After adding shim so manually to keystore binary, SafetyNet still fails.

**Comment by psychopathologist** [comment]
> ... Galaxy S20+ running android 11 and One UI 3.0

I second that (S20+ Exynos).
@kdrag0n thanks you so much!

**Comment by nampud** [comment]
Update: I removed the `code == attestKey_code` check from `interceptTransaction` (using IDA, was too lazy to compile), and SafetyNet now passes, so the method works well, only the transaction id is wrong. Nice and interesting solution!

**Comment by Praxtical** [comment]
> Update: I removed the `code == attestKey_code` check from `interceptTransaction` (using IDA, was too lazy to compile), and SafetyNet now passes, so the method works well, only the transaction id is wrong. Nice and interesting solution!
> 
> Edit: My framework.jar has `static final int TRANSACTION_attestKey = 29;`

Have an android 10 one ui 2.5 as well. I'll check for the error. Could you send it to me? Maybe I could test it.

**Comment by AByakugans** [comment]
Confirmed not working on Samsung Galaxy A600FN, arm v7, Android 10, OneUI 2.0, tested version 2.0.0fix2 + tried MagiskHide as well and nothing no change in passing CTS...

**Comment by diiegg** [comment]
As I undertand I need to flash the safetynet-fix-v2.0.0-test2.zip ? And then test again the safe net to fix the problem with the op7pro biometric ?

**Comment by Conan179** [comment]
@diiegg no flash with recovery, magisk manager.

**Comment by diiegg** [comment]
@Conan179 Got it, I already test it, still not working.... do I need to uninstall the previous version of the safety net module ?

**Comment by BlueCat300** [comment]
Android 11, OneUI 3.0 - attestation works(basic + ctsprofile true), biometric authentication in apps works.
Android 10, OneUI 2.5 - attestation not works(hardware + ctsprofile false). This device without nfc, I decided to try it just for a test.

**Comment by diiegg** [comment]
I have android 11, biometrics not working on apps, and test says not supported in my device, can use to unlock my phone but not with other apps.

I have safe net passed !!

**Comment by jkaetz** [comment]
test2 Still failing on my Tab S6.  Android 10, One UI 2.5

**Comment by t3r00t** [comment]
Using an S20 Android 11 Latest release installed and my fingerprint sensor only works for phone unlock no app fingerprint is working they are even crashing.
**A fix would be appreciated.**

**Comment by t3r00t** [comment]
# Working ! ( 2.0.0 TEST2 BUILD )
### Tested on Samsung S20 (Exynos) running Android 11 ( Both SafetyNet passed and Fingerprint are working )

**Comment by polesapart** [comment]
Xiaomi Mi9t MIUI 12 (Android 10) w/ January Security Patch: patchelf executable fails dues to missing symbol. Replaced with a working (?) version from https://github.com/linux-on-android/patchelf didn't work.

**Comment by ShaDisNX255** [comment]
Tried this solution in a Samsung Galaxy A71, running Android 10/OneUI 2.5 and it didn't work

basicIntegrity: ✓
ctsProfile: -
evalType HARDWARE

When I tried this one however: https://github.com/kdrag0n/safetynet-fix/issues/6#issuecomment-765364783

It worked like a charm. SafetyNet passes and biometrics work in apps that use them (tried it in my bank app)
And also my patched Secure Folder doesn't break anymore, as it did with the "Universal SafetyNet Fix 1.1.0.zip"
I know it was meant for a Galaxy Note 10+ but hey, if it works it works lol

**Comment by gamer13433** [comment]
On Galaxy M21 OneUI 3 works. fine. Safetynet passes and fingerprint working.

**Comment by Devo7v** [comment]
> Tried this solution in a Samsung Galaxy A71, running Android 10/OneUI 2.5 and it didn't work
> 
> basicIntegrity: ✓
> ctsProfile: -
> evalType HARDWARE
> 
> When I tried this one however: [#6 (comment)](https://github.com/kdrag0n/safetynet-fix/issues/6#issuecomment-765364783)
> 
> It worked like a charm. SafetyNet passes and biometrics work in apps that use them (tried it in my bank app)
> And also my patched Secure Folder doesn't break anymore, as it did with the "Universal SafetyNet Fix 1.1.0.zip"
> I know it was meant for a Galaxy Note 10+ but hey, if it works it works lol

I have the same experience. 2.0.0 test 2 does not fall back to basic however biometrics works in all apps. The version you linked both passes SafetyNet and biometrics works.

Samsung Galaxy S9
Android 10
OneUI 2.5
January 2021 security patch

**Comment by HennyBro** [comment]
It works on my Pixel 4 running:

- Stock Google AOSP
- January security patch level
- rooted with Magisk
- biometric face unlock works like a charm
- MagiskHide Props module is NOT NEEDED!

**Comment by Didgeridoohan** [comment]
> MagiskHide Props module is NOT NEEDED!

Correction: as long as you're using the stock (certified) ROM there's not even anything MagiskHide Props Config can do to help you pass CTS...

**Comment by Jon8RFC** [comment]
Just for grins, everything seems to be good on my non-Verizon Pixel 5, and 1.1.1 was fine as well.

**Comment by doclucas** [comment]
@kdrag0n
Besides having endless reports here of which device/os/skin it works and doesn't work on, are there any debuging steps/logs you need to to be able to adjust the module's compatibility?

**Comment by psychopathologist** [comment]
> @kdrag0n
> Besides having endless reports here of which device/os/skin it works and doesn't work on, are there any debugging steps/logs you need to to be able to adjust the module's compatibility?

On Android 10, most likely this:
https://github.com/kdrag0n/safetynet-fix/pull/13#issuecomment-767897014
(Edit part)

If you look at the patch code part for android 10, the value 28 there.

**Comment by auanasgheps** [comment]
I installed 1.1.1 and my phone was bootlooping, bu 2.0-test2 solved the issue.
I'm running Resurrection Remix (Android 10) on a Redmi Note 8T.

**Comment by kdrag0n** [comment]
@doclucas I don't need any additional info, the problem is figuring out how to detect key attestation in a more portable way. I'm not particularly interested in fixing it because I only use ROMs close to AOSP and have no interest in OEM skins, so this issue is very low priority for me.

**Comment by lekron42** [comment]
Perfectly works on S10+, A11. Thanks!

**Comment by AByakugans** [comment]
> 
> 
> @doclucas I don't need any additional info, the problem is figuring out how to detect key attestation in a more portable way. I'm not particularly interested in fixing it because I only use ROMs close to AOSP and have no interest in OEM skins, so this issue is very low priority for me.

Hello @kdrag0n can we help you make this higher prio by sending some donation or something?

**Comment by DAOWAce** [comment]
https://github.com/kdrag0n/safetynet-fix/pull/13#issuecomment-767979676

SM-T510 here, but still on Android 9 with an old TWRP recovery bootloader installed as I really dislike the changes made in Android 10.

Been tearing my hair out trying to get this to pass safetynet, as magisk props config didn't work.. and this test module also doesn't work.  The stuff linked in that other issue is too far over my head to understand.  I'm at the point where I just feel like resetting the device to stock and never having to deal with modding again.

Why Google had to go and be twats to people who wanted to be free from their device's restrictions is beyond me.

**Comment by Praxtical** [comment]
> > Edit: No errors, Cts still fails with hardware attestation. I'm on a sm-t510 running android 10 bth4 firmware and 32b arm v7
> 
> SM-T510 here, but still on Android 9 with an old TWRP recovery bootloader installed as I really dislike the changes made in Android 10.
> 
> Been tearing my hair out trying to get this to pass safetynet, as magisk props config didn't work.. and this test module also doesn't work. The stuff linked in that other issue is too far over my head to understand. I'm at the point where I just feel like resetting the device to stock and never having to deal with modding again.
> 
> Why Google had to go and be twats to people who wanted to be free from their device's restrictions is beyond me.

I honestly don't feel like I will ever reset back to stock. I'm always interested in how things work and I don't stop until I know how every little thing functions. SafetyNet isn't a big thing for me. I don't make many purchases. Maybe someday I can help with this. I don't think I'm experienced enough yet but I can try!

**Comment by Praxtical** [comment]
@kdrag0n if I were to change the supported CPU architecture, compiled it, and ran it, is the worst that could happen a boot loop/soft brick? If so id be willing to use my sm-t510 as a test dummy. I could make a nandroid backup and restore if it goes to shit lol

**Comment by AByakugans** [comment]
+1 for 32bit armv7a solution.

**Comment by jbro129** [comment]
> Tested your test2 zip on my Galaxy S20+ running android 11 and One UI 3.0. SafetyNet passes and biometric authentication seems to be working as well (Tested with paypal and my banking app).
> So far no rebooting or crashes.
> If any crashes or rebooting occur I'll update this comment or post another about it.

A follow-up to me original comment.
My device sometimes randomly restarts again after a restart. So I am restarting the device and upon getting back into my phone, the device freezes up then reboots again. It either reboots or just stays frozen resulting in me needing to force restart. One time I got a dialog saying that "System UI isn't responding". I am not sure if this is related to the module, but I will look into it.

**Comment by c3k** [comment]
Isn't working for me on S10 exynos rooted stock ROM Android 10.

After installing 2.0-test2 evalType was Hardware, seems that MagiskHide Prop was broken and I have to reconfigure it.

Now I roll back to 1.1.1 evalType is basic, but and I'm not passing basicAttestion anymore. I have MagiskHide Prop and some small system mod and never happen before.

Screenshot_20210205-074114

I will update as soon I have more info.

**Comment by Didgeridoohan** [comment]
@c3k You're also failing basic integrity, so you've got other issues. Make sure MagiskHide is enabled, if it is toggle it off and on, if things still doesn't work reboot and again check if MagiskHide is enabled. More:
https://www.didgeridoohan.com/magisk/MagiskHide#hn_SafetyNet

**Comment by c3k** [comment]
I try. MagiskHide is working, at least can suppress root request of "root checker". Did the 2.0 version of module make any change to system?

**Comment by Didgeridoohan** [comment]
@c3k If MagiskHide is otherwise working you have something else on your device that is triggering SafetyNet. Check the link in my previous post for some possible solutions, but if you want to keep discussing this is not the place for it (way off-topic). Find a suitable thread on XDA instead.

**Comment by c3k** [comment]
Yes, sure. For what I see until now problem is MagiskHide Prop realated, I will edit my first post if / when I'll find the problem.

**Comment by kdrag0n** [comment]
@Praxtical The shim solution already supports 32-bit ARM, nothing in it is architecture-specific. The old service replacement solution just needs to be recompiled.

**Comment by bwegge** [comment]
I like the idea. Unfortunately, ctsProfile fails again on EMUI 9.1.0.345 with v2.0.0-test2. With v1.1.1 it passes.

**Comment by c3k** [comment]
Seems that "test2" build works on many device and on Samsung OneUI3/A11 firmware.
With OneUI2.5/A10 I can confirm that "test2" triggers the hardware evalType, changing the keystore file as described #6 instead works.

Maybe the definitive solution should modify the device keystore during install or on the fly. I have very few scripting experience but seems not impossibile to reach.

**Comment by AByakugans** [comment]
> 
> 
> Seems that "test2" build works on many device and on Samsung OneUI3/A11 firmware.
> With OneUI2.5/A10 I can confirm that "test2" triggers the hardware evalType, changing the keystore file as described #6 instead works.
> 
> Maybe the definitive solution should modify the device keystore during install or on the fly. I have very few scripting experience but seems not impossibile to reach.

Do you have zip which can be installed in magisk on 32-bit ARM as described here https://github.com/kdrag0n/safetynet-fix/issues/6 ?

**Comment by c3k** [comment]
@AByakugans no

**Review by tata406 — APPROVED** [review]

**Comment by Praxtical** [comment]
> @Praxtical The shim solution already supports 32-bit ARM, nothing in it is architecture-specific. The old service replacement solution just needs to be recompiled.

the shim doesn't work for me, it doesn't seem to do anything and it doesn't fail either. My root method is SAR idk if that matters. maybe I could try recompiling the original for 32bit arm and seeing if I can make it work

**Comment by ninfia** [comment]
ctsProfile works with Android 12 DP1 on Google Pixel 3 XL using test2.
SafetyNet passed too.

proof

**Comment by trupf** [comment]
> > @doclucas I don't need any additional info, the problem is figuring out how to detect key attestation in a more portable way. I'm not particularly interested in fixing it because I only use ROMs close to AOSP and have no interest in OEM skins, so this issue is very low priority for me.
> 
> Hello @kdrag0n can we help you make this higher prio by sending some donation or something?

I'm just using Lineage with Open Gapps on Samsung J4+ I'm not deep in this matter but I guess Lineage is quite close to AOSP.  ctsProfile still doesn't pass althought basicIntegrity  passes with safetynet-fix-v2.0.0-test2.zip.

**Comment by trupf** [comment]
Could you tell me how to (cross-)compile this stuff? So I would try to compile it myself. Do I need the complete Android / Lineage source, or is there a way to just compile this library? Is there any other source to for compile instructions?

**Comment by kdrag0n** [comment]
Both solutions need to be compiled as part of a full ROM tree. Follow ROM compile instructions to set up your build environment. You can use the generic `aosp_arm` or `aosp_arm64` devices instead of your real one, so I'd recommend using pure AOSP instead of LineageOS or another custom ROM.

For the old solution, cherry-pick the patch in system/security and build with `m keystore`.

For the new solution, add https://github.com/kdrag0n/safetynet-fix/tree/shim/shim to vendor/shim and build with `m libkeystore_shim`.

The outputs can be found in `out/target/product/[device]`.

**Comment by TienDungVN** [comment]
I have found a Safety fix support 32bit armv7 version in xiaomi forum, it works very nice on my phone ! I think this will help some people
Link dowload (Made by Poney70): https://xiaomi.eu/community/threads/tutorial-working-fix-for-safetynet-cts-profile-failed.59384/page-5

**Comment by justneedhelp** [comment]
> For the old solution, cherry-pick the patch in system/security and build with m keystore.

Could you please describe how to do it? I'm going to apply this patch for Android x86 source tree.
I get the sources for oreo-x86 with
`repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b $branch`
`repo sync --no-tags --no-clone-bundle`

What next should I do? How to cherry-pick patch  in system/security?
I'm newbie in Android building. How to cherry-pick your patch? Thanks.

**Comment by kdrag0n** [comment]
Cherry-picking is not specific to Android. That's off-topic for this pull request, so please find a guide for cherry-picking commits with Git elsewhere and open another issue for building if you still have trouble with it.

**Comment by gvb1234** [comment]
shim method works fine on Samsung S8 with android 8. Thanks a lot.

**Comment by lukjod** [comment]
work fine on S20 ultra 5g on A11 latest rom with UI3.1

**Comment by mrambossek** [comment]
can also confirm that safetynet-fix-v2.0.0-test2.zip works fine on SM-G998B / S21 Ultra 5G with Magisk v22.0

**Comment by ppmathis** [comment]
After updating OnePlus Nord to Android 11 (OOS 11.AC01BA) with latest Magisk Stable (22.0) the current version of this module (v1.1.1 which replaces the keystore service) ends up causing a boot loop and therefore no longer seems to work. After removing the faulty module through recovery I instead tried the test archive `safetynet-fix-v2.0.0-test2.zip` with the shim implementation and can confirm that it works flawlessly.

**Comment by Oi-Baba** [comment]
OneUI Core 3.0 
The 2nd test build is working for me. Fingerprint on banking apps are also working fine.

**Comment by Marocco2** [comment]
MI9T Pro with Android 10 MIUI 12.0.4.0.

Safetynet v1.1.1 was working fine until a few days when I get a bad basicIntegrity test. Tried test2 zip but it didn't pass. basic OK cts BAD val HARDWARE.

**Comment by Oi-Baba** [comment]
> 
> 
> MI9T Pro with Android 10 MIUI 12.0.4.0.
> 
> Safetynet v1.1.1 was working fine until a few days ago when I got a bad basicIntegrity test. Tried test2 zip but it didn't pass. basic OK cts BAD val HARDWARE.

Did you flash v2 over v1.1.1?
If so remove the module, reboot then install the current one and reboot again and make sure magisk hide is on

**Comment by Marocco2** [comment]
> 
> 
> > MI9T Pro with Android 10 MIUI 12.0.4.0.
> > Safetynet v1.1.1 was working fine until a few days ago when I got a bad basicIntegrity test. Tried test2 zip but it didn't pass. basic OK cts BAD val HARDWARE.
> 
> Did you flash v2 over v1.1.1?
> If so remove the module, reboot then install the current one and reboot again and make sure magisk hide is on

No, I removed module before reboot and installing v2
MagiskHide always on

**Comment by gvb1234** [comment]
Samsung S8, Android 8, here. test2 works fine.

However, I've had random reboots with this, maybe once every 2 days. Sometimes reboot got stuck (blinking "samsung" logo on black screen, like a bootloop). No problem after manual reboot (through adb).

**Comment by terrdus** [comment]
Not working 

test2 module
Samsung Galaxy A6 (2018) SM-A600FN
One UI 2.0
Android 10
Screenshot_20210323-195027

**Comment by kdrag0n** [comment]
The continued stream of comments about when this solution works and doesn't work aren't helping to move this forward, so I'm locking the conversation until progress is made and feedback is wanted again.

Developers are free to submit PRs to improve compatibility. Details are available in #32 and #33. I have no plans to do this myself in the near future as I have no interest in the problematic ROMs and am currently busy with other projects.

**Comment by kdrag0n** [comment]
Superseded by a new solution in [v2.0.0](https://kdrag0n.dev/patreon/safetynet-fix/v2.0.0?utm_source=github).

**Pull request closed without merging**
