### PR TITLE
Play Integrity Api bypass

### PR DESCRIPTION
**Pull request by Displax**
Bypass PIA (for now?) by changing fingerprint to old "marlin" 7.1.2 (does not required to apply other security patch level).
This kills two  rabbits:
• fix old SN CTS profile check on some weird Custom ROMs
• bypass Integrity (MEETS_DEVICE_INTEGRITY) for now.

Other commit fix OnePlus OOS 12 problems ( thanks to @HuskyDG )

### CODE REVIEW

**Comment by Displax** [comment]
Close https://github.com/kdrag0n/safetynet-fix/issues/204, https://github.com/kdrag0n/safetynet-fix/issues/203, https://github.com/kdrag0n/safetynet-fix/issues/201, https://github.com/kdrag0n/safetynet-fix/issues/196, https://github.com/kdrag0n/safetynet-fix/issues/188, https://github.com/kdrag0n/safetynet-fix/issues/171, https://github.com/kdrag0n/safetynet-fix/issues/170

**Comment by kdrag0n** [comment]
Nice solution, thanks for looking into this. Have you noticed any features acting up with the old fingerprint?

Ideally, I think this should be scoped to Play Integrity code by identifying methods it calls near the beginning and end of integrity checks, and adding hooks to set and restore the fingerprint. I feel like setting a fingerprint that doesn't match the system in so many ways is bound to cause an issue somewhere.

**Comment by kdrag0n** [comment]
For example, the existing attestation hook could probably be used as a begin or end hook, depending on when Play Integrity calls it.

**Comment by Displax** [comment]
@kdrag0n 
Hi, thank you for attention! Yes, I agree with you. We need separate target hook for this (if feasible) - will be more polite solution.
My solution - just quick example (and core resolve) with temp fix for impatient people))
Though to be honest I didn't notice any problems on my side (and no one report it for now). But I think need more testing with various devices.
Anyway, you have more knowledge than me on how to do it correctly and in better way ;)

Target process (one of?) "com.android.vending/com.google.android.finsky.integrityservice.IntegrityService"

**Comment by HuskyDG** [comment]
@Displax i suggested to allow user choice the fingerprint by their own (see the example here http://github.com/huskydg/riru-integrityfix)

**Comment by kdrag0n** [comment]
Random thought: maybe the "delete key" method on the existing security provider could serve as an end hook. GMS generates a new keypair for each attestation so it probably deletes the keypair shortly afterwards.

Of course, this is all theoretical as it depends on the exact order of steps in the integrity checking process. Worst case scenario, we could just sleep for 1 second or so and revert the fingerprint change in a background thread. Not sure when I'll have time to look into it myself, but feel free to try implementing this idea:

- Set the fingerprint in the key attestation hook 
- Spawn a thread to revert it after 3 seconds:

```kotlin
thread {
    Thread.sleep(3000)
    /* Revert fingerprint */
}
```

**Comment by Displax** [comment]
@kdrag0n 
Some theoretical thought... Can we simulate device with broken keystore (like some zenfone, oneplus models)? Reported that they pass STRONG_INTEGRITY even that it completely broken.

**Comment by Lohkdesgds** [comment]
I applied the mod version, I got

✔️ MEETS_DEVICE_INTEGRITY
✔️ MEETS_BASIC_INTEGRITY
❌ MEETS_STRONG_INTEGRITY
on [integritycheck](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck) app.

Other apps like [RootBeet Sample](https://play.google.com/store/apps/details?id=com.scottyab.rootbeer.sample) and [SafetyNet Test](https://play.google.com/store/apps/details?id=org.freeandroidtools.safetynettest&hl=pt_BR&gl=US) all work great too, but they also did before this issue.

My device is an `Zenfone 6 (2019)`, fingerprint is itself.

Google Pay/Wallet working just fine (YAAAAY)

I have MagiskHideProps, Shamiko, this and a module that enables stuff on my camera. I'm new to root, but I feel great KEKW
Thank you ;P

**Comment by pndwal** [comment]
> @kdrag0n Some theoretical thought... Can we simulate device with broken keystore (like some zenfone, oneplus models)? Reported that they pass STRONG_INTEGRITY even that it completely broken.

Seems what is broken in keymaster implementations varies.

Reports I've seen indicate that affected OnePlus devices generally don't pass STRONG_INTEGRITY, whereas Rog phone 3 (for one) passes...

**Comment by Efpophis** [comment]
Hi guys, just want to let you know... I have a OnePlus 8T with the latest Android 12, rooted with latest Magisk, etc. Installing the module from this PR fixed my play store certification problem. I did have to wipe the past store app data after installing the module in order for it to pass certification. The Integrity checker app shows the strong integrity test failing, but that doesn't seem to make a difference with anything. Basic safety net stuff passes just fine.

Thank you!

**Comment by pndwal** [comment]
Re. "Req version that doesn't append a space character to the device model name" #211

@Displax, that issue makes me wonder...

It seems to me that if fingerprint should match the (expected) model as the issue suggests, then @kdrag0n's original model prop mismatch (to bypass hardware attestation enforcement) might also be produced by using a mismatched fingerprint, as your mod already does... (It is also apparent that this mismatch, at least with a very old print, causes no (known) problems for passing new MEETS_DEVICE_INTEGRITY.)

I haven't been able to test this*, but I now wonder if anyone using USNF with your 'Play Integrity Api bypass' (which introduces targeted fingerprint spoofing for gsm attestation process) actually needs altered model in addition if mismatch is achieved without it... Perhaps fingerprint spoofing can / does kill two birds... as well as two rabbits... 😛

* On my Xiaomi RN8T w/ Android 10, if I restore ro.product.model using MHPC (ie. remove appended space) and reboot, I still have S/N passing w/ official USNF, so my device doesn't need the mismatch anyway...

**Comment by Displax** [comment]
> I haven't been able to test this*, but I now wonder if anyone using USNF with your 'Play Integrity Api bypass' (which introduces targeted fingerprint spoofing for gsm attestation process) actually needs altered model in addition if mismatch is achieved without it...

Tested already, mismatched "model" still needed anyway

**Comment by ImperatorStorm** [comment]
Pixel 6 Pro, rooted with base rom with Magisk 25.2, failing `STRONG_INTEGRITY` with patch.

**Comment by Displax** [comment]
> Pixel 6 Pro, rooted with base rom with Magisk 25.2, failing `STRONG_INTEGRITY` with patch.
> Android 12

Expected

**Comment by xAffan** [comment]
> 

Anyone with ROG 3 can test? Spoofing/Replicating should be fairly easy but someone please test and post the results here

**Comment by DavidBerdik** [comment]
> @kdrag0n Some theoretical thought... Can we simulate device with broken keystore (like some zenfone, oneplus models)? Reported that they pass STRONG_INTEGRITY even that it completely broken.

Wouldn't doing this require you to reverse engineer the hardware keystore of one of the phones that have this problem?

**Comment by zanhecht** [comment]
I have Displax's mod version running on both a Pixel 3a running Android 10 and a Pixel 6a on Android 13 . The 3a shows up on my google account as a Pixel 3a, but the 6a shows up as a Nexus 6P. Is this to be expected?

**Comment by Displax** [comment]
> I have Displax's mod version running on both a Pixel 3a running Android 10 and a Pixel 6a on Android 13 . The 3a shows up on my google account as a Pixel 3a, but the 6a shows up as a Nexus 6P. Is this to be expected?

Yes

**Comment by skelletR** [comment]
> > I have Displax's mod version running on both a Pixel 3a running Android 10 and a Pixel 6a on Android 13 . The 3a shows up on my google account as a Pixel 3a, but the 6a shows up as a Nexus 6P. Is this to be expected?
> 
> Yes

If I can ask. Why the Pixel 3a android 10 show it as himself but the Pixel 6a android 13 as Nexus 6P? (Like the fingerprint in this mod)

**Comment by TheBestPessimist** [comment]
@Displax , i have tried your mod, downloaded from https://forum.xda-developers.com/t/magisk-module-universal-safetynet-fix-2-3-1.4217823/page-91#post-87198517

but unfortunately my banking app (https://play.google.com/store/apps/details?id=ro.ing.mobile.banking.android.activity) still detects something different.

More specifically: if i wipe my pixel 4a, the ING app starts and works as expected even though my bootloader is unlocked. 
After i install magisk app (and hide it) and flash the magisk modded boot image and flash your mod, the ing app does not work.

IDK if this is the right place to give you this feedback, so if you want another forum please say and mark this as spam.

**Comment by HuskyDG** [comment]
> but unfortunately my banking app (https://play.google.com/store/apps/details?id=ro.ing.mobile.banking.android.activity) still detects something different.

@TheBestPessimist this app detect zygisk

**Comment by pndwal** [comment]
> IDK if this is the right place to give you this feedback, so if you want another forum please say and mark this as spam.

It's really not; XDA Magisk General Support / Discussion or Magisk - The Age of Zygisk would be...

The purpose of USNF and this mod are to "work around Google's SafetyNet attestation" and that of the updated API, Play Integrity. It's a 'universal fix' to allow these attestations to pass... 

This module is not for hiding 'root' or associated customisations other than from processes in gsm (ie. Google Play Services)... That's the role of  Shamiko, Hide My Applist and the like... If you can pass S/N (and achieve passing deviceIntegrity verdict with this mod), USNF is doing its job! 🙂

**Comment by HuskyDG** [comment]
few people don't like closed source thing like shamiko...

**Comment by skelletR** [comment]
Very strange, today Google play store show me again the Netflix and some other apps which had been missing since July, I don't have changed anything in my phone, I have Xiaomi Poco X3 NFC android 10, magisk 23 with magisk hide com.google.android.gms.unstable and module riru 26.1.3 and Universal SafetyNet Fix 2.1.1 by kdrag0n

**Comment by josesilveiraa** [comment]
Any progress on this PR? Seems inactive by the part of kdrag0n

**Comment by DavidBerdik** [comment]
> Any progress on this PR? Seems inactive by the part of kdrag0n

I wouldn't be surprised if he's waiting for SafetyNet to get killed off before making any moves.

**Comment by pndwal** [comment]
> > Any progress on this PR? Seems inactive by the part of kdrag0n
> 
> I wouldn't be surprised if he's waiting for SafetyNet to get killed off before making any moves.

People, he's a busy guy (check his bio / 114 repos here)...

S/N is already depreciated w/ a June 2023 | Migration deadline and Full turndown slated for June 2024.

This mod is working for nearly everyone already however, and, in case any are unaware, has been available from here:
https://forum.xda-developers.com/t/magisk-module-universal-safetynet-fix-2-3-1.4217823/post-87198517
for some time now...

So as long as @kdrag0n is ok with this interim solution it seems merging official fix for new deviceIntegrity verdict is not an urgent priority... But I'm sure it's somewhere on the list. 😛

**Comment by kdrag0n** [comment]
As I explained at the beginning of this thread, I don't plan to merge this solution because it can cause issues like devices showing up as "Nexus 6P" and some device-specific features potentially not working properly. I haven't had time to work on my proposed solution, but I've already posted my thoughts on implementation details if anyone wants to take a shot at it: https://github.com/kdrag0n/safetynet-fix/pull/207#issuecomment-1200437447

Not much has changed since I posted that.

**Comment by kdrag0n** [comment]
I did try this suggestion from @Displax though:

> @kdrag0n Some theoretical thought... Can we simulate device with broken keystore (like some zenfone, oneplus models)? Reported that they pass STRONG_INTEGRITY even that it completely broken.

How broken specifically? Throwing UnsupportedOperationException from every method causes GMS to crash repeatedlyin the background, so it can't be _that_ broken. I assume that at least `load` I think we'd need a more accurate of what methods are and aren't broken if we go that route.

Breaking attestation for the unstable process was fine AFAIK, but breaking most/all of keystore seems risky and likely needs further investigation as well (if this method works).

This is what I tried:

```diff
diff --git a/java/app/src/main/java/dev/kdrag0n/safetynetfix/proxy/ProxyKeyStoreSpi.kt b/java/app/src/main/java/dev/kdrag0n/safetynetfix/proxy/ProxyKeyStoreSpi.kt
index 9005f66..314340e 100644
--- a/java/app/src/main/java/dev/kdrag0n/safetynetfix/proxy/ProxyKeyStoreSpi.kt
+++ b/java/app/src/main/java/dev/kdrag0n/safetynetfix/proxy/ProxyKeyStoreSpi.kt
@@ -39,6 +39,7 @@ class ProxyKeyStoreSpi private constructor(
 
     override fun engineGetCertificateChain(alias: String?): Array<Certificate>? {
         logDebug("Proxy key store: get certificate chain")
+        unsupported()
 
         if (isCallerSafetyNet()) {
             logDebug("Blocking call")
@@ -51,23 +52,28 @@ class ProxyKeyStoreSpi private constructor(
 
     // Direct delegation. We have to do this manually because the Kotlin compiler can only do it
     // for interfaces, not abstract classes.
-    override fun engineGetKey(alias: String?, password: CharArray?): Key? = orig.engineGetKey(alias, password)
-    override fun engineGetCertificate(alias: String?): Certificate? = orig.engineGetCertificate(alias)
-    override fun engineGetCreationDate(alias: String?): Date? = orig.engineGetCreationDate(alias)
-    override fun engineSetKeyEntry(alias: String?, key: Key?, password: CharArray?, chain: Array<out Certificate>?) = orig.engineSetKeyEntry(alias, key, password, chain)
-    override fun engineSetKeyEntry(alias: String?, key: ByteArray?, chain: Array<out Certificate>?) = orig.engineSetKeyEntry(alias, key, chain)
-    override fun engineSetCertificateEntry(alias: String?, cert: Certificate?) = orig.engineSetCertificateEntry(alias, cert)
-    override fun engineDeleteEntry(alias: String?) = orig.engineDeleteEntry(alias)
-    override fun engineAliases(): Enumeration<String>? = orig.engineAliases()
-    override fun engineContainsAlias(alias: String?) = orig.engineContainsAlias(alias)
-    override fun engineSize() = orig.engineSize()
-    override fun engineIsKeyEntry(alias: String?) = orig.engineIsKeyEntry(alias)
-    override fun engineIsCertificateEntry(alias: String?) = orig.engineIsCertificateEntry(alias)
-    override fun engineGetCertificateAlias(cert: Certificate?): String? = orig.engineGetCertificateAlias(cert)
-    override fun engineStore(stream: OutputStream?, password: CharArray?) = orig.engineStore(stream, password)
-    override fun engineLoad(stream: InputStream?, password: CharArray?) = orig.engineLoad(stream, password)
+    override fun engineGetKey(alias: String?, password: CharArray?): Key? = unsupported()
+    override fun engineGetCertificate(alias: String?): Certificate? = unsupported()
+    override fun engineGetCreationDate(alias: String?): Date? = unsupported()
+    override fun engineSetKeyEntry(alias: String?, key: Key?, password: CharArray?, chain: Array<out Certificate>?) = unsupported()
+    override fun engineSetKeyEntry(alias: String?, key: ByteArray?, chain: Array<out Certificate>?) = unsupported()
+    override fun engineSetCertificateEntry(alias: String?, cert: Certificate?) = unsupported()
+    override fun engineDeleteEntry(alias: String?) = unsupported()
+    override fun engineAliases(): Enumeration<String>? = unsupported()
+    override fun engineContainsAlias(alias: String?) = unsupported()
+    override fun engineSize() = unsupported()
+    override fun engineIsKeyEntry(alias: String?) = unsupported()
+    override fun engineIsCertificateEntry(alias: String?) = unsupported()
+    override fun engineGetCertificateAlias(cert: Certificate?): String? = unsupported()
+    override fun engineStore(stream: OutputStream?, password: CharArray?) = unsupported()
+    override fun engineLoad(stream: InputStream?, password: CharArray?) = unsupported()
 
     companion object {
         @Volatile internal var androidImpl: KeyStoreSpi? = null
     }
 }
+
+private fun unsupported(): Nothing {
+    logDebug("callKS unsupported", Exception())
+    throw UnsupportedOperationException()
+}
```

**Comment by kdrag0n** [comment]
I did actually look at this briefly in July but I was passing Play Integrity (excl. strong, of course) out-of-the-box with the last stable version of the module, so I couldn't test any attempted fixes. Testing setup was Pixel 6 + Android 13 Beta 3. Is there something I'm missing?

**Comment by pndwal** [comment]
>... Is there something I'm missing?

I'm not up with how the code works (or how Google might adjust attestation for devices flagged as have flawed keymaster), but the statement re. 'devices with broken keystore (like some zenfone, oneplus models)' that it's
> Reported that they pass STRONG_INTEGRITY even that it completely broken.

seems to be flawed in part.

As I mentioned above:
> Seems what is broken in keymaster implementations varies.
> 
> Reports I've seen indicate that affected OnePlus devices generally don't pass STRONG_INTEGRITY, whereas Rog phone 3 (for one) passes...

AFAIK this Asus device may be the only device where strongIntegrity passes w/ unlocked bootloader and mods... Hope it helps...

**Comment by kdrag0n** [comment]
> > ... Is there something I'm missing?
> 
> I'm not up with how the code works (or how Google might adjust attestation for devices flagged as having flawed keymaster), but the statement re. 'devices with broken keystore (like some zenfone, oneplus models)' that it's

Sorry, to clarify: that comment isn't related to the broken keystore idea. The issue is that I couldn't test anything because I couldn't get Play Integrity to _not_ pass on my Pixel 6 with Android 13 Beta 3.

**Comment by pndwal** [comment]
I do know this mainly affects A11+ devices (I haven't needed any such mod on my Xiaomi device w/ A10 MIUI either), but timing varies... Google seems to have done much server end fiddling since PI implementation... XDA G Pay thread (as well as your USNF thread) indicates deviceIntegrity failing or simply resolving itself inexplicably for those w/o Displax modded USNF on many different occasions... Applying the mod usually resolves things...

As an example I see Pixel 6 Pro (w/ September stock A13 ROM update) was passing fine till Sept 24... Something reportedly changed for 6 Pro that day and user resolved issue w/ Displax USNF mod.
https://forum.xda-developers.com/t/discussion-google-pay-magisk-discussion-thread.3906703/post-87481197

... Guess you could try updating Pixel 6 A13 Beta 3 to official stock A13 too, but for all I know Google may have also reverted changes for Pixel 6 Pro,  Pixel 6, other (?) since implementing them!... Such is the state of flux that is PI ATM...

**Comment by Displax** [comment]
@kdrag0n 

> How broken specifically? Throwing UnsupportedOperationException from every method causes GMS to crash repeatedlyin the background, so it can't be _that_ broken. I assume that at least `load` I think we'd need a more accurate of what methods are and aren't broken if we go that route.

Yep, I am tested some variants too, but did not find specific identifiers. Maybe some sort of exclusion list (whitelist) for that devices like this public "bad" list: https://android.googleapis.com/attestation/status


> Sorry, to clarify: that comment isn't related to the broken keystore idea. The issue is that I couldn't test anything because I couldn't get Play Integrity to _not_ pass on my Pixel 6 with Android 13 Beta 3.

As i know, DP/Beta releases added to whitelist to pass SN/PI in almost all cases. So it`s need to be testing on release builds.

**Review by HuskyDG — COMMENTED** [review]
The detection apps will know they are fooled if you have Android 13 but release version is Android 6. The game is more funny! 😂

**Comment by kdrag0n** [comment]
Update: It's been a while, but I finally had time to look at this again now that I can reproduce it. I've found a trigger point for only spoofing the fingerprint transiently and will release a new version with the change soon.

I'll close this PR after that and I prefer #225 for the Pixel 7 fix, but @Displax feel free to submit the OnePlus fix in a separate PR. Thanks for looking into this first!

**Comment by Displax** [comment]
@kdrag0n 
> I'll close this PR after that and I prefer #225 for the Pixel 7 fix, but @Displax feel free to submit the OnePlus fix in a separate PR. Thanks for looking into this first!

Separate PR: https://github.com/kdrag0n/safetynet-fix/pull/240

**Comment by kdrag0n** [comment]
[v2.4.0 early access](https://github.com/kdrag0n/safetynet-fix/releases/tag/v2.4.0-ea) has been released with a dynamic Play Integrity workaround to avoid breaking device checks or causing other problems. Thanks again @Displax for kickstarting this work!

It's taken a while to find way to bypass Play Integrity that doesn't require spoofing the build fingerprint permanently, but I wanted to make sure this module doesn't cause any unnecessary breakage. Just like the original goal of Universal SafetyNet Fix, this minimizes adverse effects by spoofing dynamically at runtime only when necessary. Enjoy!

For some context: I don't usually do early access releases for USNF anymore unless the majority of the release is my original work. I feel like it's justified in this case as I had to put the work into finding a dynamic/scoped workaround.

**Comment by knox** [comment]
> Ideally, I think this should be scoped to Play Integrity code by identifying methods it calls near the beginning and end of integrity checks, and adding hooks to set and restore the fingerprint

> released with a dynamic Play Integrity workaround

> it's taken a while to find way to bypass Play Integrity that doesn't require spoofing the build fingerprint permanently

Maybe i'm just not getting things right but i was curious about the details and couldn't find anything like this in the recent commit history. Could you please guide me a bit?

**Comment by DavidBerdik** [comment]
@knox I'm pretty sure that the reason that you can't find it is because he hasn't released the code for it yet.

> For context: I don't usually do early access releases for USNF anymore unless the majority of the release is my original work. I feel like it's justified in this case as I had to put the work into finding a dynamic/scoped workaround. Associated issues will be closed when 2.4.0 is released publicly.

**Comment by knox** [comment]
> the reason that you can't find it is because he hasn't released the code for it yet.

> This version is currently in early access. [Download on Patreon](https://www.patreon.com/posts/76675472)

silly me

**Comment by DavidBerdik** [comment]
> silly me

It's fine. 😆 Happens to all of us now and then.

**Review by cxulo — APPROVED** [review]

**Review by cxulo — APPROVED** [review]

**Pull request closed without merging**
