### PR TITLE
Support update.json Magisk update checker

### PR DESCRIPTION
**Pull request by benjibobs**
This adds the update.json file used in Magisk v24 and above, as defined at https://topjohnwu.github.io/Magisk/guides.html#moduleprop. This is also discussed briefly in #136.

The json is populated for v2.2.1, so will have to be bumped alongside module.props whenever a new version is released.

### CODE REVIEW

**Comment by kdrag0n** [comment]
Thanks! It looks like the changelog is supposed to be plain text though, so I'm not sure about that part.

**Comment by ipdev99** [comment]
> Thanks! It looks like the changelog is supposed to be plain text though, so I'm not sure about that part.
I mentioned this in the Magisk General xda thread including an example module.prop and update json file.

https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/#post-86307943

**Comment by benjibobs** [comment]
Thanks for the info @ipdev99 :) I'll update the PR with a fixed json pointing to a changelog file based on existing github releases tomorrow.

**Comment by ipdev99** [comment]
> Thanks for the info @ipdev99 :) I'll update the PR with a fixed json pointing to a changelog file based on existing github releases tomorrow.

The only thing I would recommend is to name the _json_ file more specific.
Example: _safetynetfix.json_ or _usnf.json_

That way it can be hosted together with other _json_ files.
_Example: https://github.com/topjohnwu/magisk-files_

**Comment by benjibobs** [comment]
I decided to keep the filename 'update.json' for now as it is hosted within this repo, so I feel it's more descriptive to keep it as such. Of course, if @kdrag0n decides to centralize the json files then I agree that a better name is 'safetynet-fix.json' :)

I compiled the changelog from the releases/tags and added the donation notice right at the top. Let me know if you'd rather have this in a different format!

**Comment by kdrag0n** [comment]
Thanks! I might make a few tweaks before making a release with this, but it looks great overall. Sorry for the delay.

**Pull request merged**
