### PR TITLE
Update for Android 12 Beta 3

### PR DESCRIPTION
**Pull request by bleez99**
Minor changes
Rename SDK directory to 31 from 31-b2
Grep for the new build version string SPB3 in customize.sh and service.sh
Assign variables accordingly in the shell scripts.

### CODE REVIEW

**Review by davwheat — APPROVED** [review]
Confirmed working on Pixel 3 XL. Great job! 👍

**Comment by bleez99** [comment]
> Confirmed working on Pixel 3 XL. Great job! +1
> 
> [safetynet-fix-a12.3.zip](https://github.com/kdrag0n/safetynet-fix/files/6929451/safetynet-fix-a12.3.zip)

Thank you.

I think at this point we can safely remove the script changes as we do return 31 for the SDK.  That's no longer a moving target.  The only thing in question now is will the patches still work once 12 is officially released.  Probably so, but I can wait.  I'm sure @kdrag0n is waiting for the same, as this is his project.  I did the minimum to keep things running.

**Comment by kdrag0n** [comment]
Sorry for the delay. I didn't want to ship a Beta 3 build with old binaries because it could cause hidden breakage. Closing because Beta 4 requires new binaries.

**Comment by bleez99** [comment]
> Sorry for the delay. I didn't want to ship a Beta 3 build with old binaries because it could cause hidden breakage. Closing because Beta 4 requires new binaries.

Thanks.  I thought as much, but using the Beta 2 binaries on Beta 3 worked out for me in every way.  Went on vacation and GPayed my a** off, no issues whatsoever.  I rolled the dice with Beta 4 and lost the bet.  I'll patiently wait for Beta 4 binaries if you plan to build them.  Great job, I appreciate your efforts.

**Pull request closed without merging**
